let boxContainer = [
    {
        whatBox: "shirt",
        whatTitleBox: "لباس ها",
        // icon: "https://img.icons8.com/material/96/00427d/t-shirt--v1.png",
        icon: "https://img.icons8.com/material/96/00427d/fireman-coat.png",

    },
    {
        whatBox: "hat",
        whatTitleBox: "کلاه ها",
        icon: "https://img.icons8.com/material/96/00427d/trilby.png",

    },
    {
        whatBox: "shoes",
        whatTitleBox: "کفش ها",
        icon: "https://img.icons8.com/material/96/00427d/boots.png",
    },
]

let allProduct = [
    // shirt Products 
    {
        id: 0,
        category: "shirt",
        title: "لباس تستی",
        imgSrc: "images/products/shirt/product-image-3.jpg",
        bottomImage1: "images/products/shirt/product-image-4.jpg",
        bottomImage2: "images/products/shirt/product-image-5.jpg",
        bottomImage3: "images/products/shirt/product-image-4.jpg",
        bottomImage4: "images/products/shirt/product-image-3.jpg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد، کتابهای زیادی در شصت و سه درصد گذشته حال و آینده، شناخت فراوان جامعه و متخصصان را می طلبد، تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و فرهنگ پیشرو در زبان فارسی ایجاد کرد، در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها، و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی، و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.",
    },
    {
        id: 1,
        category: "shirt",
        title: "لباس تستی",
        imgSrc: "images/products/shirt/product-image-4.jpg",
        bottomImage1: "images/products/shirt/product-image-4.jpg",
        bottomImage2: "images/products/shirt/product-image-4.jpg",
        bottomImage3: "images/products/shirt/product-image-4.jpg",
        bottomImage4: "images/products/shirt/product-image-4.jpg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد، کتابهای زیادی در شصت و سه درصد گذشته حال و آینده، شناخت فراوان جامعه و متخصصان را می طلبد، تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و فرهنگ پیشرو در زبان فارسی ایجاد کرد، در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها، و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی، و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.",
    },
    {
        id: 2,
        category: "shirt",
        title: "لباس تستی",
        imgSrc: "images/products/shirt/product-image-5.jpg",
        bottomImage1: "images/products/shirt/product-image-5.jpg",
        bottomImage2: "images/products/shirt/product-image-5.jpg",
        bottomImage3: "images/products/shirt/product-image-5.jpg",
        bottomImage4: "images/products/shirt/product-image-5.jpg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد، کتابهای زیادی در شصت و سه درصد گذشته حال و آینده، شناخت فراوان جامعه و متخصصان را می طلبد، تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و فرهنگ پیشرو در زبان فارسی ایجاد کرد، در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها، و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی، و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.",
    },
    {
        id: 3,
        category: "shirt",
        title: "لباس تستی",
        imgSrc: "images/products/shirt/product-image-6.jpg",
        bottomImage1: "images/products/shirt/product-image-6.jpg",
        bottomImage2: "images/products/shirt/product-image-6.jpg",
        bottomImage3: "images/products/shirt/product-image-6.jpg",
        bottomImage4: "images/products/shirt/product-image-6.jpg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد، کتابهای زیادی در شصت و سه درصد گذشته حال و آینده، شناخت فراوان جامعه و متخصصان را می طلبد، تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و فرهنگ پیشرو در زبان فارسی ایجاد کرد، در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها، و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی، و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.",
    },
    {
        id: 4,
        category: "shirt",
        title: "لباس تستی",
        imgSrc: "images/products/shirt/product-image-7.jpg",
        bottomImage1: "images/products/shirt/product-image-7.jpg",
        bottomImage2: "images/products/shirt/product-image-7.jpg",
        bottomImage3: "images/products/shirt/product-image-7.jpg",
        bottomImage4: "images/products/shirt/product-image-7.jpg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد، کتابهای زیادی در شصت و سه درصد گذشته حال و آینده، شناخت فراوان جامعه و متخصصان را می طلبد، تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و فرهنگ پیشرو در زبان فارسی ایجاد کرد، در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها، و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی، و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.",
    },
    {
        id: 5,
        category: "shirt",
        title: "لباس تستی",
        imgSrc: "images/products/shirt/product-image-5.jpg",
        bottomImage1: "images/products/shirt/product-image-5.jpg",
        bottomImage2: "images/products/shirt/product-image-5.jpg",
        bottomImage3: "images/products/shirt/product-image-5.jpg",
        bottomImage4: "images/products/shirt/product-image-5.jpg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد، کتابهای زیادی در شصت و سه درصد گذشته حال و آینده، شناخت فراوان جامعه و متخصصان را می طلبد، تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و فرهنگ پیشرو در زبان فارسی ایجاد کرد، در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها، و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی، و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.",
    },
    {
        id: 6,
        category: "shirt",
        title: "لباس تستی",
        imgSrc: "images/products/shirt/product-image-6.jpg",
        bottomImage1: "images/products/shirt/product-image-6.jpg",
        bottomImage2: "images/products/shirt/product-image-6.jpg",
        bottomImage3: "images/products/shirt/product-image-6.jpg",
        bottomImage4: "images/products/shirt/product-image-6.jpg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد، کتابهای زیادی در شصت و سه درصد گذشته حال و آینده، شناخت فراوان جامعه و متخصصان را می طلبد، تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و فرهنگ پیشرو در زبان فارسی ایجاد کرد، در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها، و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی، و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.",
    },
    {
        id: 7,
        category: "shirt",
        title: "لباس تستی",
        imgSrc: "images/products/shirt/product-image-7.jpg",
        bottomImage1: "images/products/shirt/product-image-7.jpg",
        bottomImage2: "images/products/shirt/product-image-7.jpg",
        bottomImage3: "images/products/shirt/product-image-7.jpg",
        bottomImage4: "images/products/shirt/product-image-7.jpg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد، کتابهای زیادی در شصت و سه درصد گذشته حال و آینده، شناخت فراوان جامعه و متخصصان را می طلبد، تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و فرهنگ پیشرو در زبان فارسی ایجاد کرد، در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها، و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی، و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.",
    },

    // hat Products 
    {
        id: 8,
        category: "hat",
        title: "کلاه تستی",
        imgSrc: "images/products/hats/product-image-1.jpg",
        bottomImage1: "images/products/hats/product-image-1.jpg",
        bottomImage2: "images/products/hats/product-image-1.jpg",
        bottomImage3: "images/products/hats/product-image-1.jpg",
        bottomImage4: "images/products/hats/product-image-1.jpg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد، کتابهای زیادی در شصت و سه درصد گذشته حال و آینده، شناخت فراوان جامعه و متخصصان را می طلبد، تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و فرهنگ پیشرو در زبان فارسی ایجاد کرد، در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها، و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی، و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.",
    },
    {
        id: 9,
        category: "hat",
        title: "کلاه تستی",
        imgSrc: "images/products/hats/product-image-1.jpg",
        bottomImage1: "images/products/hats/product-image-1.jpg",
        bottomImage2: "images/products/hats/product-image-1.jpg",
        bottomImage3: "images/products/hats/product-image-1.jpg",
        bottomImage4: "images/products/hats/product-image-1.jpg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد، کتابهای زیادی در شصت و سه درصد گذشته حال و آینده، شناخت فراوان جامعه و متخصصان را می طلبد، تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و فرهنگ پیشرو در زبان فارسی ایجاد کرد، در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها، و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی، و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.",
    },
    {
        id: 10,
        category: "hat",
        title: "کلاه تستی",
        imgSrc: "images/products/hats/product-image-1.jpg",
        bottomImage1: "images/products/hats/product-image-1.jpg",
        bottomImage2: "images/products/hats/product-image-1.jpg",
        bottomImage3: "images/products/hats/product-image-1.jpg",
        bottomImage4: "images/products/hats/product-image-1.jpg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد، کتابهای زیادی در شصت و سه درصد گذشته حال و آینده، شناخت فراوان جامعه و متخصصان را می طلبد، تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و فرهنگ پیشرو در زبان فارسی ایجاد کرد، در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها، و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی، و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.",
    },
    {
        id: 11,
        category: "hat",
        title: "کلاه تستی",
        imgSrc: "images/products/hats/product-image-1.jpg",
        bottomImage1: "images/products/hats/product-image-1.jpg",
        bottomImage2: "images/products/hats/product-image-1.jpg",
        bottomImage3: "images/products/hats/product-image-1.jpg",
        bottomImage4: "images/products/hats/product-image-1.jpg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد، کتابهای زیادی در شصت و سه درصد گذشته حال و آینده، شناخت فراوان جامعه و متخصصان را می طلبد، تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و فرهنگ پیشرو در زبان فارسی ایجاد کرد، در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها، و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی، و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.",
    },
    {
        id: 12,
        category: "hat",
        title: "کلاه تستی",
        imgSrc: "images/products/hats/product-image-1.jpg",
        bottomImage1: "images/products/hats/product-image-1.jpg",
        bottomImage2: "images/products/hats/product-image-1.jpg",
        bottomImage3: "images/products/hats/product-image-1.jpg",
        bottomImage4: "images/products/hats/product-image-1.jpg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد، کتابهای زیادی در شصت و سه درصد گذشته حال و آینده، شناخت فراوان جامعه و متخصصان را می طلبد، تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و فرهنگ پیشرو در زبان فارسی ایجاد کرد، در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها، و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی، و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.",
    },
    {
        id: 13,
        category: "hat",
        title: "کلاه تستی",
        imgSrc: "images/products/hats/product-image-1.jpg",
        bottomImage1: "images/products/hats/product-image-1.jpg",
        bottomImage2: "images/products/hats/product-image-1.jpg",
        bottomImage3: "images/products/hats/product-image-1.jpg",
        bottomImage4: "images/products/hats/product-image-1.jpg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد، کتابهای زیادی در شصت و سه درصد گذشته حال و آینده، شناخت فراوان جامعه و متخصصان را می طلبد، تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و فرهنگ پیشرو در زبان فارسی ایجاد کرد، در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها، و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی، و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.",
    },
    {
        id: 14,
        category: "hat",
        title: "کلاه تستی",
        imgSrc: "images/products/hats/product-image-1.jpg",
        bottomImage1: "images/products/hats/product-image-1.jpg",
        bottomImage2: "images/products/hats/product-image-1.jpg",
        bottomImage3: "images/products/hats/product-image-1.jpg",
        bottomImage4: "images/products/hats/product-image-1.jpg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد، کتابهای زیادی در شصت و سه درصد گذشته حال و آینده، شناخت فراوان جامعه و متخصصان را می طلبد، تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و فرهنگ پیشرو در زبان فارسی ایجاد کرد، در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها، و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی، و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.",
    },
    {
        id: 15,
        category: "hat",
        title: "کلاه تستی",
        imgSrc: "images/products/hats/product-image-1.jpg",
        bottomImage1: "images/products/hats/product-image-1.jpg",
        bottomImage2: "images/products/hats/product-image-1.jpg",
        bottomImage3: "images/products/hats/product-image-1.jpg",
        bottomImage4: "images/products/hats/product-image-1.jpg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد، کتابهای زیادی در شصت و سه درصد گذشته حال و آینده، شناخت فراوان جامعه و متخصصان را می طلبد، تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و فرهنگ پیشرو در زبان فارسی ایجاد کرد، در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها، و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی، و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.",
    },

    // shoes Products
    {
        id: 16,
        category: "shoes",
        title: "لباس تستی",
        imgSrc: "images/products/shoes/product-image-24.jpeg",
        bottomImage1: "images/products/shoes/product-image-24.jpeg",
        bottomImage2: "images/products/shoes/product-image-24.jpeg",
        bottomImage3: "images/products/shoes/product-image-24.jpeg",
        bottomImage4: "images/products/shoes/product-image-24.jpeg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد، کتابهای زیادی در شصت و سه درصد گذشته حال و آینده، شناخت فراوان جامعه و متخصصان را می طلبد، تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و فرهنگ پیشرو در زبان فارسی ایجاد کرد، در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها، و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی، و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.",
    },
    {
        id: 17,
        category: "shoes",
        title: "لباس تستی",
        imgSrc: "images/products/shoes/product-image-19.jpeg",
        bottomImage1: "images/products/shoes/product-image-19.jpeg",
        bottomImage2: "images/products/shoes/product-image-19.jpeg",
        bottomImage3: "images/products/shoes/product-image-19.jpeg",
        bottomImage4: "images/products/shoes/product-image-19.jpeg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد، کتابهای زیادی در شصت و سه درصد گذشته حال و آینده، شناخت فراوان جامعه و متخصصان را می طلبد، تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و فرهنگ پیشرو در زبان فارسی ایجاد کرد، در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها، و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی، و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.",
    },
    {
        id: 18,
        category: "shoes",
        title: "لباس تستی",
        imgSrc: "images/products/shoes/product-image-20.jpeg",
        bottomImage1: "images/products/shoes/product-image-20.jpeg",
        bottomImage2: "images/products/shoes/product-image-20.jpeg",
        bottomImage3: "images/products/shoes/product-image-20.jpeg",
        bottomImage4: "images/products/shoes/product-image-20.jpeg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد، کتابهای زیادی در شصت و سه درصد گذشته حال و آینده، شناخت فراوان جامعه و متخصصان را می طلبد، تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و فرهنگ پیشرو در زبان فارسی ایجاد کرد، در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها، و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی، و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.",
    },
    {
        id: 19,
        category: "shoes",
        title: "لباس تستی",
        imgSrc: "images/products/shoes/product-image-21.jpeg",
        bottomImage1: "images/products/shoes/product-image-21.jpeg",
        bottomImage2: "images/products/shoes/product-image-21.jpeg",
        bottomImage3: "images/products/shoes/product-image-21.jpeg",
        bottomImage4: "images/products/shoes/product-image-21.jpeg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد، کتابهای زیادی در شصت و سه درصد گذشته حال و آینده، شناخت فراوان جامعه و متخصصان را می طلبد، تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و فرهنگ پیشرو در زبان فارسی ایجاد کرد، در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها، و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی، و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.",
    },
    {
        id: 20,
        category: "shoes",
        title: "لباس تستی",
        imgSrc: "images/products/shoes/product-image-22.jpeg",
        bottomImage1: "images/products/shoes/product-image-22.jpeg",
        bottomImage2: "images/products/shoes/product-image-22.jpeg",
        bottomImage3: "images/products/shoes/product-image-22.jpeg",
        bottomImage4: "images/products/shoes/product-image-22.jpeg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد، کتابهای زیادی در شصت و سه درصد گذشته حال و آینده، شناخت فراوان جامعه و متخصصان را می طلبد، تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و فرهنگ پیشرو در زبان فارسی ایجاد کرد، در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها، و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی، و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.",
    },
    {
        id: 21,
        category: "shoes",
        title: "لباس تستی",
        imgSrc: "images/products/shoes/product-image-23.jpeg",
        bottomImage1: "images/products/shoes/product-image-23.jpeg",
        bottomImage2: "images/products/shoes/product-image-23.jpeg",
        bottomImage3: "images/products/shoes/product-image-23.jpeg",
        bottomImage4: "images/products/shoes/product-image-23.jpeg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد، کتابهای زیادی در شصت و سه درصد گذشته حال و آینده، شناخت فراوان جامعه و متخصصان را می طلبد، تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و فرهنگ پیشرو در زبان فارسی ایجاد کرد، در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها، و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی، و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.",
    },
    {
        id: 22,
        category: "shoes",
        title: "لباس تستی",
        imgSrc: 'images/products/shoes/product-image-18.jpeg',
        bottomImage1: "images/products/shoes/product-image-18.jpeg",
        bottomImage2: "images/products/shoes/product-image-18.jpeg",
        bottomImage3: "images/products/shoes/product-image-18.jpeg",
        bottomImage4: "images/products/shoes/product-image-18.jpeg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد، کتابهای زیادی در شصت و سه درصد گذشته حال و آینده، شناخت فراوان جامعه و متخصصان را می طلبد، تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و فرهنگ پیشرو در زبان فارسی ایجاد کرد، در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها، و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی، و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.",
    },
    {
        id: 23,
        category: "shoes",
        title: "لباس تستی",
        imgSrc: "images/products/shoes/product-image-21.jpeg",
        bottomImage1: "images/products/shoes/product-image-21.jpeg",
        bottomImage2: "images/products/shoes/product-image-21.jpeg",
        bottomImage3: "images/products/shoes/product-image-21.jpeg",
        bottomImage4: "images/products/shoes/product-image-21.jpeg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد، کتابهای زیادی در شصت و سه درصد گذشته حال و آینده، شناخت فراوان جامعه و متخصصان را می طلبد، تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و فرهنگ پیشرو در زبان فارسی ایجاد کرد، در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها، و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی، و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.",
    },
    {
        id: 24,
        category: "shoes",
        title: "لباس تستی",
        imgSrc: "images/products/shoes/product-image-23.jpeg",
        bottomImage1: "images/products/shoes/product-image-23.jpeg",
        bottomImage2: "images/products/shoes/product-image-23.jpeg",
        bottomImage3: "images/products/shoes/product-image-23.jpeg",
        bottomImage4: "images/products/shoes/product-image-23.jpeg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد، کتابهای زیادی در شصت و سه درصد گذشته حال و آینده، شناخت فراوان جامعه و متخصصان را می طلبد، تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و فرهنگ پیشرو در زبان فارسی ایجاد کرد، در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها، و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی، و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.",
    },
    {
        id: 25,
        category: "shoes",
        title: "لباس تستی",
        imgSrc: "images/products/shoes/product-image-24.jpeg",
        bottomImage1: "images/products/shoes/product-image-24.jpeg",
        bottomImage2: "images/products/shoes/product-image-24.jpeg",
        bottomImage3: "images/products/shoes/product-image-24.jpeg",
        bottomImage4: "images/products/shoes/product-image-24.jpeg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد، کتابهای زیادی در شصت و سه درصد گذشته حال و آینده، شناخت فراوان جامعه و متخصصان را می طلبد، تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و فرهنگ پیشرو در زبان فارسی ایجاد کرد، در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها، و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی، و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.",
    },
    {
        id: 26,
        category: "shoes",
        title: "لباس تستی",
        imgSrc: "images/products/shoes/product-image-21.jpeg",
        bottomImage1: "images/products/shoes/product-image-21.jpeg",
        bottomImage2: "images/products/shoes/product-image-21.jpeg",
        bottomImage3: "images/products/shoes/product-image-21.jpeg",
        bottomImage4: "images/products/shoes/product-image-21.jpeg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد، کتابهای زیادی در شصت و سه درصد گذشته حال و آینده، شناخت فراوان جامعه و متخصصان را می طلبد، تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و فرهنگ پیشرو در زبان فارسی ایجاد کرد، در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها، و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی، و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.",
    },
]

let customersLogo = [
    {
        id: 0,
        className: "anata",
        imgSrc: "images/logo/Anata-logo.png"
    },
    {
        id: 1,
        className: "kanaf-iran",
        imgSrc: "images/logo/Kanaf-Iran-logo.png"
    },
    {
        id: 3,
        className: "khoshgovar",
        imgSrc: "images/logo/Khoshgovar-logo.png"
    },
    {
        id: 4,
        className: "Parsiangostar",
        imgSrc: "images/logo/Parsiangostar-logo.png"
    },
    {
        id: 13,
        className: "parssimin",
        imgSrc: "images/logo/Parssimin-logo.png"
    },
]

let whyus = [
    {
        id: 0,
        postTitle: "دوخت تضمینی",
        imgSrc: "https://img.icons8.com/material/96/00427d/needle.png",
        content: "لباسکار یکی از نیاز های فردی در کسب و کار و فعالیت ها حسوب می شود که امروزه در هر زمینه نیاز پرسنلی شرکت ها و کارخانه ها و هم در بخش تبلیغات کاربرد زیادی دارد که یکی از مهم ترین چیزهایی که این نیاز را برطرف میکند داشتن یک دوخت کاملا مناسب و تضمین این کیفیت و دوخت میباشد که رعایت کردن این موضوع سبب رضایت مندی مشتری از کار ارایه شده می شود"
    },
    {
        id: 1,
        postTitle: "کیفیت برتر",
        imgSrc: "https://img.icons8.com/material/96/00427d/guarantee.png",
        content: "یکی دیگر از گزینه های مهم در خط یک تولید مناسب کیفیت مناسب کار می باشد که شامل رعایت کیفیت در تمامی موارد از جمله پارچه , دوخت زیپ , آستر , دکمه و چسب و ... می باشد که اگر تمامی این موارد از کیفیت خوبی برخوردار باشد پایان کار , یک پایان کار ایده ال خواهد بود"
    },
    {
        id: 2,
        postTitle: "کیفیت پارچه",
        imgSrc: "https://img.icons8.com/material/96/00427d/t-shirt--v1.png",
        content: "کیفیت پارچه ها را با توجه به نیاز مشتری بابت تامین لباس کار میتوان دسته بندی کردکه گاها به صورت جنس ایده ال , درجه یک و معمولی انجام پذیر است که این انتخابه درجه پارچه ها معمولا با توجه به بودجه شرکت ها در جهت تامین لباس کار برای واحد های مختلف انتخاب می شود"
    },
    {
        id: 3,
        postTitle: "رنگ بندی البسه",
        imgSrc: "https://img.icons8.com/material/96/00427d/paint-palette--v1.png",
        content: "لباس ها را در خط تولید می توان با مدل ها و رنگ بندی های مختلف اجرا کرد که این انتخاب رنگ و مدل با توجه به سلیقه مشتریان انجام می پذیرد که معمولا رنگ بندی لباس ها طبق برند سازمانی اعمال می شود"
    },
    {
        id: 4,
        postTitle: "چاپ و گلدوزی",
        imgSrc: "https://img.icons8.com/material/96/00427d/embroidery.png",
        content: "کاملا مشخص است که هدف از تولید یک لباس کار نشان دادن برند شرکت سفارش دهنده است که با توجه به سلیقه مشتریان به دو حالت چاپ و گلدوزی طبق لوگو سازمانی شرکت مربوطه قابل اجرا می باشد "
    },
    {
        id: 5,
        postTitle: "چاپ و گلدوزی",
        imgSrc: "https://img.icons8.com/material/96/00427d/embroidery.png",
        content: "کاملا مشخص است که هدف از تولید یک لباس کار نشان دادن برند شرکت سفارش دهنده است که با توجه به سلیقه مشتریان به دو حالت چاپ و گلدوزی طبق لوگو سازمانی شرکت مربوطه قابل اجرا می باشد "
    },
]

