let boxContainer = [
    {
        whatBox: "shert",
        whatTitleBox: "لباس های <br> ایمن کارکو",
    },
    {
        whatBox: "hat",
        whatTitleBox: "کلاه های <br> ایمن کارکو",
    },
    {
        whatBox: "shoose",
        whatTitleBox: "کفش های <br> ایمن کارکو",
    },
]

let allProduct = [
    // shert Products 
    {
        id: 0,
        category: "shert",
        title: "لباس تستی",
        imgSrc: "images/products/sherts/product-image-3.jpg",
        mainImage: "images/products/sherts/product-image-3.jpg",
        bottomImage1: "images/products/sherts/product-image-3.jpg",
        bottomImage2: "images/products/sherts/product-image-3.jpg",
        bottomImage3: "images/products/sherts/product-image-3.jpg",
        bottomImage4: "images/products/sherts/product-image-3.jpg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "توضیحات",
    },
    {
        id: 1,
        category: "shert",
        title: "لباس تستی",
        imgSrc: "images/products/sherts/product-image-4.jpg",
        mainImage: "images/products/sherts/product-image-4.jpg",
        bottomImage1: "images/products/sherts/product-image-4.jpg",
        bottomImage2: "images/products/sherts/product-image-4.jpg",
        bottomImage3: "images/products/sherts/product-image-4.jpg",
        bottomImage4: "images/products/sherts/product-image-4.jpg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "توضیحات",
    },
    {
        id: 2,
        category: "shert",
        title: "لباس تستی",
        imgSrc: "images/products/sherts/product-image-5.jpg",
        mainImage: "images/products/sherts/product-image-5.jpg",
        bottomImage1: "images/products/sherts/product-image-5.jpg",
        bottomImage2: "images/products/sherts/product-image-5.jpg",
        bottomImage3: "images/products/sherts/product-image-5.jpg",
        bottomImage4: "images/products/sherts/product-image-5.jpg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "توضیحات",
    },
    {
        id: 3,
        category: "shert",
        title: "لباس تستی",
        imgSrc: "images/products/sherts/product-image-6.jpg",
        mainImage: "images/products/sherts/product-image-6.jpg",
        bottomImage1: "images/products/sherts/product-image-6.jpg",
        bottomImage2: "images/products/sherts/product-image-6.jpg",
        bottomImage3: "images/products/sherts/product-image-6.jpg",
        bottomImage4: "images/products/sherts/product-image-6.jpg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "توضیحات",
    },
    {
        id: 4,
        category: "shert",
        title: "لباس تستی",
        imgSrc: "images/products/sherts/product-image-7.jpg",
        mainImage: "images/products/sherts/product-image-7.jpg",
        bottomImage1: "images/products/sherts/product-image-7.jpg",
        bottomImage2: "images/products/sherts/product-image-7.jpg",
        bottomImage3: "images/products/sherts/product-image-7.jpg",
        bottomImage4: "images/products/sherts/product-image-7.jpg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "توضیحات",
    },
    {
        id: 5,
        category: "shert",
        title: "لباس تستی",
        imgSrc: "images/products/sherts/product-image-5.jpg",
        mainImage: "images/products/sherts/product-image-5.jpg",
        bottomImage1: "images/products/sherts/product-image-5.jpg",
        bottomImage2: "images/products/sherts/product-image-5.jpg",
        bottomImage3: "images/products/sherts/product-image-5.jpg",
        bottomImage4: "images/products/sherts/product-image-5.jpg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "توضیحات",
    },
    {
        id: 6,
        category: "shert",
        title: "لباس تستی",
        imgSrc: "images/products/sherts/product-image-6.jpg",
        mainImage: "images/products/sherts/product-image-6.jpg",
        bottomImage1: "images/products/sherts/product-image-6.jpg",
        bottomImage2: "images/products/sherts/product-image-6.jpg",
        bottomImage3: "images/products/sherts/product-image-6.jpg",
        bottomImage4: "images/products/sherts/product-image-6.jpg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "توضیحات",
    },
    {
        id: 7,
        category: "shert",
        title: "لباس تستی",
        imgSrc: "images/products/sherts/product-image-7.jpg",
        mainImage: "images/products/sherts/product-image-7.jpg",
        bottomImage1: "images/products/sherts/product-image-7.jpg",
        bottomImage2: "images/products/sherts/product-image-7.jpg",
        bottomImage3: "images/products/sherts/product-image-7.jpg",
        bottomImage4: "images/products/sherts/product-image-7.jpg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "توضیحات",
    },

    // hat Products 
    {
        id: 8,
        category: "hat",
        title: "کلاه تستی",
        imgSrc: "images/products/hats/product-image-1.jpg",
        mainImage: "images/products/hats/product-image-1.jpg",
        bottomImage1: "images/products/hats/product-image-1.jpg",
        bottomImage2: "images/products/hats/product-image-1.jpg",
        bottomImage3: "images/products/hats/product-image-1.jpg",
        bottomImage4: "images/products/hats/product-image-1.jpg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "توضیحات",
    },
    {
        id: 9,
        category: "hat",
        title: "کلاه تستی",
        imgSrc: "images/products/hats/product-image-1.jpg",
        mainImage: "images/products/hats/product-image-1.jpg",
        bottomImage1: "images/products/hats/product-image-1.jpg",
        bottomImage2: "images/products/hats/product-image-1.jpg",
        bottomImage3: "images/products/hats/product-image-1.jpg",
        bottomImage4: "images/products/hats/product-image-1.jpg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "توضیحات",
    },
    {
        id: 10,
        category: "hat",
        title: "کلاه تستی",
        imgSrc: "images/products/hats/product-image-1.jpg",
        mainImage: "images/products/hats/product-image-1.jpg",
        bottomImage1: "images/products/hats/product-image-1.jpg",
        bottomImage2: "images/products/hats/product-image-1.jpg",
        bottomImage3: "images/products/hats/product-image-1.jpg",
        bottomImage4: "images/products/hats/product-image-1.jpg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "توضیحات",
    },
    {
        id: 11,
        category: "hat",
        title: "کلاه تستی",
        imgSrc: "images/products/hats/product-image-1.jpg",
        mainImage: "images/products/hats/product-image-1.jpg",
        bottomImage1: "images/products/hats/product-image-1.jpg",
        bottomImage2: "images/products/hats/product-image-1.jpg",
        bottomImage3: "images/products/hats/product-image-1.jpg",
        bottomImage4: "images/products/hats/product-image-1.jpg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "توضیحات",
    },
    {
        id: 12,
        category: "hat",
        title: "کلاه تستی",
        imgSrc: "images/products/hats/product-image-1.jpg",
        mainImage: "images/products/hats/product-image-1.jpg",
        bottomImage1: "images/products/hats/product-image-1.jpg",
        bottomImage2: "images/products/hats/product-image-1.jpg",
        bottomImage3: "images/products/hats/product-image-1.jpg",
        bottomImage4: "images/products/hats/product-image-1.jpg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "توضیحات",
    },
    {
        id: 13,
        category: "hat",
        title: "کلاه تستی",
        imgSrc: "images/products/hats/product-image-1.jpg",
        mainImage: "images/products/hats/product-image-1.jpg",
        bottomImage1: "images/products/hats/product-image-1.jpg",
        bottomImage2: "images/products/hats/product-image-1.jpg",
        bottomImage3: "images/products/hats/product-image-1.jpg",
        bottomImage4: "images/products/hats/product-image-1.jpg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "توضیحات",
    },
    {
        id: 14,
        category: "hat",
        title: "کلاه تستی",
        imgSrc: "images/products/hats/product-image-1.jpg",
        mainImage: "images/products/hats/product-image-1.jpg",
        bottomImage1: "images/products/hats/product-image-1.jpg",
        bottomImage2: "images/products/hats/product-image-1.jpg",
        bottomImage3: "images/products/hats/product-image-1.jpg",
        bottomImage4: "images/products/hats/product-image-1.jpg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "توضیحات",
    },
    {
        id: 15,
        category: "hat",
        title: "کلاه تستی",
        imgSrc: "images/products/hats/product-image-1.jpg",
        mainImage: "images/products/hats/product-image-1.jpg",
        bottomImage1: "images/products/hats/product-image-1.jpg",
        bottomImage2: "images/products/hats/product-image-1.jpg",
        bottomImage3: "images/products/hats/product-image-1.jpg",
        bottomImage4: "images/products/hats/product-image-1.jpg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "توضیحات",
    },

    // shoose Products
    {
        id: 16,
        category: "shoose",
        title: "لباس تستی",
        imgSrc: 'images/products/shoose/product-image-18.jpeg',
        mainImage: "images/products/shoose/product-image-18.jpeg",
        bottomImage1: "images/products/shoose/product-image-18.jpeg",
        bottomImage2: "images/products/shoose/product-image-18.jpeg",
        bottomImage3: "images/products/shoose/product-image-18.jpeg",
        bottomImage4: "images/products/shoose/product-image-18.jpeg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "توضیحات",
    },
    {
        id: 17,
        category: "shoose",
        title: "لباس تستی",
        imgSrc: "images/products/shoose/product-image-19.jpeg",
        mainImage: "images/products/shoose/product-image-19.jpeg",
        bottomImage1: "images/products/shoose/product-image-19.jpeg",
        bottomImage2: "images/products/shoose/product-image-19.jpeg",
        bottomImage3: "images/products/shoose/product-image-19.jpeg",
        bottomImage4: "images/products/shoose/product-image-19.jpeg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "توضیحات",
    },
    {
        id: 18,
        category: "shoose",
        title: "لباس تستی",
        imgSrc: "images/products/shoose/product-image-20.jpeg",
        mainImage: "images/products/shoose/product-image-20.jpeg",
        bottomImage1: "images/products/shoose/product-image-20.jpeg",
        bottomImage2: "images/products/shoose/product-image-20.jpeg",
        bottomImage3: "images/products/shoose/product-image-20.jpeg",
        bottomImage4: "images/products/shoose/product-image-20.jpeg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "توضیحات",
    },
    {
        id: 19,
        category: "shoose",
        title: "لباس تستی",
        imgSrc: "images/products/shoose/product-image-21.jpeg",
        mainImage: "images/products/shoose/product-image-21.jpeg",
        bottomImage1: "images/products/shoose/product-image-21.jpeg",
        bottomImage2: "images/products/shoose/product-image-21.jpeg",
        bottomImage3: "images/products/shoose/product-image-21.jpeg",
        bottomImage4: "images/products/shoose/product-image-21.jpeg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "توضیحات",
    },
    {
        id: 20,
        category: "shoose",
        title: "لباس تستی",
        imgSrc: "images/products/shoose/product-image-22.jpeg",
        mainImage: "images/products/shoose/product-image-22.jpeg",
        bottomImage1: "images/products/shoose/product-image-22.jpeg",
        bottomImage2: "images/products/shoose/product-image-22.jpeg",
        bottomImage3: "images/products/shoose/product-image-22.jpeg",
        bottomImage4: "images/products/shoose/product-image-22.jpeg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "توضیحات",
    },
    {
        id: 21,
        category: "shoose",
        title: "لباس تستی",
        imgSrc: "images/products/shoose/product-image-23.jpeg",
        mainImage: "images/products/shoose/product-image-23.jpeg",
        bottomImage1: "images/products/shoose/product-image-23.jpeg",
        bottomImage2: "images/products/shoose/product-image-23.jpeg",
        bottomImage3: "images/products/shoose/product-image-23.jpeg",
        bottomImage4: "images/products/shoose/product-image-23.jpeg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "توضیحات",
    },
    {
        id: 22,
        category: "shoose",
        title: "لباس تستی",
        imgSrc: "images/products/shoose/product-image-24.jpeg",
        mainImage: "images/products/shoose/product-image-24.jpeg",
        bottomImage1: "images/products/shoose/product-image-24.jpeg",
        bottomImage2: "images/products/shoose/product-image-24.jpeg",
        bottomImage3: "images/products/shoose/product-image-24.jpeg",
        bottomImage4: "images/products/shoose/product-image-24.jpeg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "توضیحات",
    },
    {
        id: 23,
        category: "shoose",
        title: "لباس تستی",
        imgSrc: "images/products/shoose/product-image-21.jpeg",
        mainImage: "images/products/shoose/product-image-21.jpeg",
        bottomImage1: "images/products/shoose/product-image-21.jpeg",
        bottomImage2: "images/products/shoose/product-image-21.jpeg",
        bottomImage3: "images/products/shoose/product-image-21.jpeg",
        bottomImage4: "images/products/shoose/product-image-21.jpeg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "توضیحات",
    },
    {
        id: 24,
        category: "shoose",
        title: "لباس تستی",
        imgSrc: "images/products/shoose/product-image-23.jpeg",
        mainImage: "images/products/shoose/product-image-23.jpeg",
        bottomImage1: "images/products/shoose/product-image-23.jpeg",
        bottomImage2: "images/products/shoose/product-image-23.jpeg",
        bottomImage3: "images/products/shoose/product-image-23.jpeg",
        bottomImage4: "images/products/shoose/product-image-23.jpeg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "توضیحات",
    },
    {
        id: 25,
        category: "shoose",
        title: "لباس تستی",
        imgSrc: "images/products/shoose/product-image-24.jpeg",
        mainImage: "images/products/shoose/product-image-24.jpeg",
        bottomImage1: "images/products/shoose/product-image-24.jpeg",
        bottomImage2: "images/products/shoose/product-image-24.jpeg",
        bottomImage3: "images/products/shoose/product-image-24.jpeg",
        bottomImage4: "images/products/shoose/product-image-24.jpeg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "توضیحات",
    },
    {
        id: 26,
        category: "shoose",
        title: "لباس تستی",
        imgSrc: "images/products/shoose/product-image-21.jpeg",
        mainImage: "images/products/shoose/product-image-21.jpeg",
        bottomImage1: "images/products/shoose/product-image-21.jpeg",
        bottomImage2: "images/products/shoose/product-image-21.jpeg",
        bottomImage3: "images/products/shoose/product-image-21.jpeg",
        bottomImage4: "images/products/shoose/product-image-21.jpeg",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        material: "تستی",
        description: "توضیحات",
    },
]

let customersLogo = [
    {
        id: 0,
        className: "anata",
        imgSrc: "images/logo/Anata-logo.png"
    },
    {
        id: 1,
        className: "kanaf-iran",
        imgSrc: "images/logo/Kanaf-Iran-logo.png"
    },
    {
        id: 2,
        className: "sumsung",
        imgSrc: "images/logo/sumsung-logo.png"
    },
    {
        id: 3,
        className: "khoshgovar",
        imgSrc: "images/logo/Khoshgovar-logo.png"
    },
    {
        id: 4,
        className: "anata",
        imgSrc: "images/logo/Parsiangostar-logo.png"
    },
    {
        id: 5,
        className: "pouyesh-pajouhan",
        imgSrc: "images/logo/Pouyesh-pajouhan-logo.png"
    },
    {
        id: 6,
        className: "abidi",
        imgSrc: "images/logo/Abidi-logo.png"
    },
    {
        id: 7,
        className: "akhavan",
        imgSrc: "images/logo/Parskhazar-logo.png"
    },
    {
        id: 8,
        className: "parskhazar",
        imgSrc: "images/logo/Akhavan-logo.png"
    },
    {
        id: 9,
        className: "ramak",
        imgSrc: "images/logo/Ramak-logo.png"
    },
    {
        id: 10,
        className: "casterol",
        imgSrc: "images/logo/Casterol-logo.png"
    },
    {
        id: 11,
        className: "goushtiran",
        imgSrc: "images/logo/Goushtiran-logo.png"
    },
    {
        id: 12,
        className: "snowa",
        imgSrc: "images/logo/Snowa-logo.png"
    },
    {
        id: 13,
        className: "parssimin",
        imgSrc: "images/logo/Parssimin-logo.png"
    },
]

let whyus = [
    {
        postTitle: "دوخت تضمینی",
        imgSrc: "images/icons/thread-icon.png",
        content: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز"
    },
    {
        postTitle: "دوخت تضمینی",
        imgSrc: "images/icons/thread-icon.png",
        content: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز"
    },
    {
        postTitle: "دوخت تضمینی",
        imgSrc: "images/icons/thread-icon.png",
        content: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز"
    },
    {
        postTitle: "دوخت تضمینی",
        imgSrc: "images/icons/thread-icon.png",
        content: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز"
    },
    {
        postTitle: "دوخت تضمینی",
        imgSrc: "images/icons/thread-icon.png",
        content: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز"
    },
    {
        postTitle: "دوخت تضمینی",
        imgSrc: "images/icons/thread-icon.png",
        content: "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز"
    },
]

